### ISSUE TITLE
Remove abandoned package eloquent/pops

### ISSUE THREAD

**Issue by Daanvm** [eloquent/liberator#4]
Since the `eloquent/pops` library is archived, composer marks it as abandoned. This results in a warning when installing `eloquent/liberator`. This package should not depend on abandoned packages.

![Screenshot 2020-02-12 at 15 59 53](https://user-images.githubusercontent.com/1397121/74347188-006e4c00-4db1-11ea-8d55-4770878f0a7d.png)

I'm happy to make a PR if someone can explain what the idea was of archiving `eloquent/pops` and what the suggested alternative is.

**Comment by ezzatron** [comment]
Ah, sorry about that. I was a bit to eager to mark pops as archived, and forgot that this package depends on it. I've removed the flag until I can properly remove the dependency.

**Comment by Daanvm** [comment]
Thanks 👍

**Comment by Ilyes512** [comment]
It is still giving me the warning... I think you need to login to Packagist itself and "un-abandon" it to resolve this (if you still think it should not be abandoned that is): https://packagist.org/packages/eloquent/pops

**Comment by ezzatron** [comment]
Weird, could have sworn I un-abandoned it. I've just done it again. Let me know if it continues to be an issue 👍
